name: Lint, Test and Build

on:
  push:
    # branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    outputs:
      build-number: ${{ steps.build-number-job.outputs.BUILD_NUMBER }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set build number
        id: build-number-job
        run: echo "BUILD_NUMBER=v1.0.0" >> "$GITHUB_OUTPUT"

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Deploy
        shell: bash
        run: |
          echo "Deployment script goes here!"

      - name: Get build number
        env:
          BUILD_NUMBER: ${{ needs.build.outputs.build-number }}
        run: echo "Build number is $BUILD_NUMBER"
